# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f8538c6b38471a93196249a2a16e64aae299afe9319376d8880d416e52e09cfc188ea091ba67898a93e0afbd2c218643bb651ee15df876e369d603531f8059f

test:
  secret_key_base: dbed5c6374b284ee249d295e12141031c2bb9c6a6d121ac855237077598d0f07607bca2f424de85ff76a3479f555a8877662bbe47625068977619f0928466325

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
